// Real customer reviews, quoted from our Yelp and Thumbtack pages. Keep the text verbatim when adding more.
// Don't add review/rating structured data (JSON-LD): Google ignores self-serving LocalBusiness reviews.
export const YELP_URL = "https://www.yelp.com/biz/movers-and-junk-removal-north-las-vegas-4";
export const THUMBTACK_URL =
  "https://www.thumbtack.com/nv/north-las-vegas/moving-companies/movers-junk-removal-llc/service/584925992855920661";

export const REVIEW_SOURCES = {
  // Logos are cropped to their content (public/*-logo.png; Thumbtack rearranged side by side so it reads at badge size).
  // width/height are the files' pixel sizes; scale evens out their visual size next to each other.
  yelp: { label: "Yelp", url: YELP_URL, logo: { src: "/yelp-logo.png", width: 632, height: 241, scale: 1 } },
  thumbtack: { label: "Thumbtack", url: THUMBTACK_URL, logo: { src: "/thumbtack-logo.png", width: 701, height: 104, scale: 0.7 } },
} as const;

export type Review = { src: keyof typeof REVIEW_SOURCES; text: string; who: string; tags: ("moving" | "junk" | "same-day")[] };

// Order matters: reviewsFor() and the home page show the first few, so the strongest go first.
export const REVIEWS: Review[] = [
  { src: "yelp", tags: ["junk", "same-day"], text: "Highly recommend! They were very responsive, able to do a same-day pickup, and the whole process was quick and efficient. Great communication, best pricing, and everything was gone in no time. I'll definitely be using them again!", who: "Camille C." },
  { src: "thumbtack", tags: ["moving"], text: "I had a great experience booking them for my move to Las Vegas from Miami. Very professional and helpful. They gave me great pricing and even helped me with mounting my TVs on the wall for me. We didn’t make it to Vegas as scheduled but they were more than accommodating with my arrival time and day even made themselves available to come a couple hours earlier than agreed upon time to knock out the job earlier. We definitely would use Juan and his crew again as well as recommend them to others. You can’t go wrong! Thank you guys!", who: "Terry F." },
  { src: "thumbtack", tags: ["junk"], text: "If you're looking for reliable movers or junk removal services, I highly recommend Movers and Junk Removal LLC. They helped me remove several items from my yard, including some very heavy pieces that I couldn't have moved on my own. Super great pricing and what impressed me most was how responsive they were. They got back to me almost immediately, scheduled the job quickly, and took care of everything efficiently. The entire process was simple, fast, and stress free. I would definitely use them again and would recommend them to anyone looking for dependable moving or junk removal services.", who: "Amelia G." },
  { src: "yelp", tags: ["moving"], text: "I cannot say enough good things about Juan and his team. I hired them to unload heavy items from my pod and assemble new furniture. They were incredibly polite, friendly, and helpful. The job was completed efficiently, and although the assembly of my daughter's bunkbed took longer than expected due to so many pieces, they made it priority to finish and ensure it was done correctly. Also cannot beat the price. I would definitely hire again!", who: "Natalie M." },
  { src: "yelp", tags: ["junk", "same-day"], text: "Had a great experience with this company. Juan responded right away, gave me a real quote and it was very reasonable, and he and his crew came that day. No hidden fees and everything is up front pricing. It was 2 people and they got rid of my sectional quickly, within 20 mins. Would use again. Give them a call :)", who: "Jinny L." },
  { src: "thumbtack", tags: ["moving"], text: "Great experience with these guys. Very punctual and made everything go smoothly. They brought plastic wrap and wrapped my furniture for me as well. Highly recommend", who: "Cassandra L." },
  { src: "thumbtack", tags: ["moving", "junk"], text: "I had a great experience with Movers & Junk Removal! They were professional, reliable, and very respectful throughout the entire process. They showed up on time, worked efficiently, and handled everything with care. The pricing was fair, and the whole experience was smooth and stress-free. I definitely recommend Movers & Junk Removal to anyone who needs help with moving or getting rid of unwanted items. Great service from start to finish!", who: "Marvin B." },
  { src: "thumbtack", tags: ["moving"], text: "I was nervous hiring someone I didn’t know but Juan was very professional and easy to work with . His price was very fair , he was communicative and did great work . I will definitely use him again!", who: "Denise S." },
  { src: "yelp", tags: ["moving"], text: "I needed help assembling my blackstone griddle & my kids bunk bed, so glad that I found Movers & junk removal! Juan came thru with one of his guys and knocked the job out in just a few hours and did an amazing job! Not only that, I was having trouble igniting my blackstone the next day and Juan drove 30+ minutes to help just to make sure the job was complete. I couldn't ask for a better person for the job! He also gave me a great price for the job as well. Whether you need help moving, furniture assembly, and even junk removal Juan is your man for the job. I'd give these guys 10 stars if I could!", who: "Cam R." },
  { src: "thumbtack", tags: ["moving"], text: "I had a great experience with this moving company from start to finish. The team was professional, punctual, and handled all of my belongings with care. They worked efficiently, communicated well throughout the move, and made what could have been a stressful day feel easy and organized. I truly appreciate their hard work and excellent customer service. I would definitely recommend them to anyone looking for a reliable and trustworthy moving company. Thank you for making my move such a smooth experience! God bless.", who: "Waheema P." },
  { src: "thumbtack", tags: ["moving", "same-day"], text: "These guys are so good. The owner met me the next day and was there to help me in a pinch. He was friendly, professional all the above. I’ll definitely use them again.", who: "Melinda L." },
  { src: "thumbtack", tags: ["junk", "same-day"], text: "This company is great, and responded very quickly to my request to move some junk. Showed up early and got the job done quickly. Would hire again in the future. Definitely recommend them.", who: "David N." },
  { src: "thumbtack", tags: ["moving"], text: "Great experience! They arrived ready to work and helped move and rearrange furniture around my home. They were professional, efficient, and got everything exactly where I needed it. I was honestly impressed that they completed the entire job in about 10 minutes! Everything went smoothly from start to finish. I would definitely recommend them and use their services again.", who: "Shanell W." },
  { src: "thumbtack", tags: ["moving"], text: "The guys showed up on time, ready & prepared to move my stuff from storage unit to storage unit. Nothing was damaged along the way and it was a quick move lasting only an hour which was quicker than I had anticipated. Great job Movers and Junk Removal!", who: "Carla G." },
  { src: "thumbtack", tags: ["moving", "same-day"], text: "I'm so thankful for the last minute help with my move. Very kind and professional movers. Highly recommend!", who: "Bradley L." },
  { src: "thumbtack", tags: ["moving"], text: "Great price and they come with their own van so that helps cut the cost ! Arrived on time and was quick and friendly. Will be hiring again if needed!", who: "Zsuelle A." },
  { src: "thumbtack", tags: ["moving"], text: "I had a great experience with this moving company from start to finish. The team was professional, friendly, and handled everything with care. Showed up on time, worked efficiently, and made what could have been a stressful move feel smooth and easy.", who: "Stephen B." },
  { src: "thumbtack", tags: ["moving"], text: "Great experience. Juan and his crew were professional and courteous. From the moment I contacted the company to the moment they were done it was a great experience", who: "Mario M." },
  { src: "thumbtack", tags: ["moving"], text: "Amazing service highly recommended Wrap the Furniture really well clients were really happy with the service. Highly recommended.", who: "Ulysses W." },
  { src: "thumbtack", tags: ["moving"], text: "He is very professional and caring. Great in communications with your needs. Fast, helpful takes pride in his work. Cares about your needs. I would recommend him. Could not for a better mover.", who: "Jane R." },
  { src: "thumbtack", tags: ["moving"], text: "This was an awesome experience reasonably priced, kind, friendly and respectful. They did a quick job, very efficient, I would hire this team again!", who: "Pamela J." },
  { src: "thumbtack", tags: ["moving"], text: "These guys are legit, they showed up on time, moved all of our items with care and worked quickly. 10/10 recommend", who: "Emily K." },
  { src: "thumbtack", tags: ["junk"], text: "Will use them again in the future! great professionalism and fast work with removing the items I needed.", who: "Sam H." },
  { src: "thumbtack", tags: ["moving"], text: "They were great! Did an amazing job and very professional .. I will be using them again and highly recommended", who: "Alia L." },
  { src: "thumbtack", tags: ["moving"], text: "Dude was on it… from start to finish. Will trust 100% again for similar jobs in the future.", who: "Eissa H." },
  { src: "thumbtack", tags: ["moving"], text: "Highly recommend these movers. They were organized, careful, and very courteous.", who: "Jesse M." },
  { src: "thumbtack", tags: ["moving"], text: "Well priced, good communication did a really good job. 👍🏾", who: "Mike J." },
  { src: "yelp", tags: ["moving", "junk"], text: "Very professional and up front with the pricing. Thank you guys for all the help! AAA+++", who: "Andrew G." },
];

export const reviewsFor = (tag: Review["tags"][number], n = 3) => REVIEWS.filter((r) => r.tags.includes(tag)).slice(0, n);
